-- ============================================================================
-- Heard base schema (staging)
-- ============================================================================
-- These tables predate Heard's committed migration history (they were created
-- ad-hoc / by Figma Make in the production project), so no migration in Heard's
-- `supabase/migrations/` creates them. This file fills that gap so a fresh local
-- database matches production closely enough to run the app.
--
-- It runs FIRST (timestamp 0). Heard's own migrations (synced in alongside this
-- file) run afterward and create the rest: votes, llm_api_calls, flyer_scans,
-- phone_submissions, statement_merges, user_events, and the ALTER that adds
-- `reason` to user_reports below.
--
-- The shapes here are derived from `src/supabase/*.sql` and the TypeScript types
-- in `src/supabase/functions/server/types.tsx`. For an authoritative copy, run
-- `npm run dump:remote` against the production DB (see README).
-- ============================================================================

-- The Heard edge function talks to the DB as `service_role`. The local stack
-- does NOT automatically grant migration-created tables to the Supabase API
-- roles, which produces "permission denied for table ..." errors. Setting
-- default privileges FIRST (as the migration role) makes every table/sequence
-- created afterward — by this file AND by Heard's synced migrations — accessible.
grant usage on schema public to anon, authenticated, service_role;
alter default privileges in schema public grant all on tables to anon, authenticated, service_role;
alter default privileges in schema public grant all on sequences to anon, authenticated, service_role;

-- The core key-value store. ~all app data (users, rooms, statements, votes,
-- sessions, communities, ...) lives here as JSONB.
create table if not exists kv_store_f1a393b4 (
  key   text  not null primary key,
  value jsonb not null
);

-- Engagement tracking (src/supabase/cover_card_swipes_table.sql).
create table if not exists cover_card_swipes (
  id         bigserial primary key,
  "userId"   text   not null,
  "roomId"   text   not null,
  "swipedAt" bigint not null,
  unique ("userId", "roomId")
);
create index if not exists idx_cover_card_swipes_user_id on cover_card_swipes ("userId");

-- src/supabase/room_follows_table.sql
create table if not exists room_follows (
  id           bigserial primary key,
  "userId"     text   not null,
  "roomId"     text   not null,
  "followedAt" bigint not null,
  unique ("userId", "roomId")
);
create index if not exists idx_room_follows_user_id on room_follows ("userId");

-- src/supabase/room_views_table.sql
create table if not exists room_views (
  id           bigserial primary key,
  "userId"     text   not null,
  "roomId"     text   not null,
  "lastSeenAt" bigint not null,
  unique ("userId", "roomId")
);
create index if not exists idx_room_views_user_id on room_views ("userId");

-- Realtime presence (model-utils.ts: upsert on "userId"; lastUpdated is an ISO string).
create table if not exists presences (
  "userId"           text not null primary key,
  "currentRoomIndex" int,
  "avatarAnimal"     text,
  "lastUpdated"      timestamptz not null default now()
);

-- Reporting (types.tsx UserReport). `reason` is added by Heard's
-- 20260427000000_add_reason_to_user_reports migration, so it is omitted here.
create table if not exists user_reports (
  id               uuid primary key default gen_random_uuid(),
  "responseId"     text not null,
  "reportingUserId" text not null,
  "createdAt"      timestamptz not null default now()
);

-- Demographics feature (types.tsx DemographicQuestion / DemographicAnswer).
create table if not exists demographic_questions (
  id        bigint generated by default as identity primary key,
  "roomId"  text not null,
  type      text not null,
  text      text,
  options   jsonb
);
create index if not exists idx_demographic_questions_room_id on demographic_questions ("roomId");

create table if not exists demographic_answers (
  id           bigint generated by default as identity primary key,
  "userId"     text not null,
  "questionId" bigint not null,
  answer       text,
  "createdAt"  bigint not null default (extract(epoch from now()) * 1000)::bigint,
  unique ("userId", "questionId")
);
create index if not exists idx_demographic_answers_question_id on demographic_answers ("questionId");

-- Events feature (types.tsx Event).
create table if not exists events (
  id              bigint generated by default as identity primary key,
  name            text not null,
  subtitle        text,
  "communityName" text,
  "creatorId"     text not null,
  "createdAt"     bigint not null default (extract(epoch from now()) * 1000)::bigint
);

-- Internal config flags (model-utils.ts internal_vars; value is JSON-stringified).
create table if not exists internal_vars (
  key   text not null primary key,
  value text not null
);

-- Email capture (model-utils.ts).
create table if not exists flyer_emails (
  id          bigint generated by default as identity primary key,
  email       text not null,
  "createdAt" timestamptz not null default now()
);

create table if not exists org_signups (
  id          bigint generated by default as identity primary key,
  email       text not null,
  "createdAt" timestamptz not null default now()
);
